[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools-scm[toml]>=6.2"
]
build-backend = "setuptools.build_meta"

[project]
name = "py-tree-sitter-spthy"
description = "Tree-sitter parser for Spthy language"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Luca Mandrelli"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Linguistic",
]
requires-python = ">=3.8"
dependencies = [
    "tree-sitter>=0.20.0",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "black",
    "flake8",
]

[project.urls]
Homepage = "https://github.com/lmandrelli/py-tree-sitter-spthy"
Repository = "https://github.com/lmandrelli/py-tree-sitter-spthy"
Issues = "https://github.com/lmandrelli/py-tree-sitter-spthy/issues"

[tool.setuptools_scm]
write_to = "py_tree_sitter_spthy/_version.py"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]